package xyzhealthcare.healthcareeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ClaimID")
   private java.lang.Integer claimID;

   @org.kie.api.definition.type.Label(value = "Claim Date")
   private java.util.Date claimDate;

   @org.kie.api.definition.type.Label(value = "Claim Amt")
   private java.lang.Float claimAmount;

   @org.kie.api.definition.type.Label(value = "Eligibility")
   private java.lang.Boolean eligibility;

   public Claim()
   {
   }

   public java.lang.Integer getClaimID()
   {
      return this.claimID;
   }

   public void setClaimID(java.lang.Integer claimID)
   {
      this.claimID = claimID;
   }

   public java.util.Date getClaimDate()
   {
      return this.claimDate;
   }

   public void setClaimDate(java.util.Date claimDate)
   {
      this.claimDate = claimDate;
   }

   public java.lang.Float getClaimAmount()
   {
      return this.claimAmount;
   }

   public void setClaimAmount(java.lang.Float claimAmount)
   {
      this.claimAmount = claimAmount;
   }

   public java.lang.Boolean getEligibility()
   {
      return this.eligibility;
   }

   public void setEligibility(java.lang.Boolean eligibility)
   {
      this.eligibility = eligibility;
   }

   public Claim(java.lang.Integer claimID, java.util.Date claimDate,
         java.lang.Float claimAmount, java.lang.Boolean eligibility)
   {
      this.claimID = claimID;
      this.claimDate = claimDate;
      this.claimAmount = claimAmount;
      this.eligibility = eligibility;
   }

}