package xyzhealthcare.healthcareeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("state")
   private java.lang.String state;
   @org.kie.api.definition.type.Label("income")
   private java.lang.Float income;
   @org.kie.api.definition.type.Label("elegibilty")
   private boolean eligibility;

   public Customer()
   {
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Float getIncome()
   {
      return this.income;
   }

   public void setIncome(java.lang.Float income)
   {
      this.income = income;
   }

   public boolean isEligibility()
   {
      return this.eligibility;
   }

   public void setEligibility(boolean eligibility)
   {
      this.eligibility = eligibility;
   }

   public Customer(java.lang.String state, java.lang.Float income,
         boolean eligibility)
   {
      this.state = state;
      this.income = income;
      this.eligibility = eligibility;
   }

}